# Generated by Django 3.2.12 on 2024-10-02 04:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Membre',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('noms', models.CharField(max_length=100, unique=True, verbose_name='Nom complet')),
                ('date_adhesion', models.DateField(auto_now_add=True, verbose_name="Date d'adhésion")),
                ('image', models.ImageField(blank=True, null=True, upload_to='auth/images/', verbose_name='Image de profil')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Membre du staff')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Auteur',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('noms', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('noms', models.CharField(max_length=100)),
                ('qte_livre', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Livre',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('noms', models.CharField(max_length=100)),
                ('date_edition', models.DateField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='livre/images/')),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lib.auteur')),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lib.categorie')),
            ],
        ),
        migrations.CreateModel(
            name='Emprunt',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('duree', models.IntegerField()),
                ('paiement', models.CharField(choices=[('MM', 'Mobile Money'), ('CC', 'Credit Card'), ('BTC', 'Bitcoin')], default='MM', max_length=10)),
                ('livre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lib.livre')),
                ('membre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
